config/routes.rb
Rails.application.routes.draw do
  get 'all' => 'flowers#index'

  resources :flowers

  root 'static_pages#home'

end

app/models/flower.rb
class Flower < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  def index
  	@flowers = Flower.all
  end

  def show
  	@flower = Flower.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Provides the title for each page.
	def full_title(page_title = '')
		base_title = "Flowers"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/flowers/index.html.erb
<h1>List of all flowers</h1>
<ul>
	<% @flowers.each do |flower| %>
		<li><%= link_to flower.name, flower %></li>
	<% end %>
</ul>

app/views/flowers/show.html.erb
<h1><%= @flower.name %></h1>
<p class="lead">
	<%= @flower.about %>
</p>
<%= image_tag(@flower.image_url) %>
<br/>
<%= link_to "Back to all flowers", all_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Flowers", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "All", all_path %></li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title><%= full_title(yield(:title)) %></title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
  	<%= favicon_link_tag 'favicon.ico' %>
  	<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
	<h1>The Teaching of Flowers</h1>
	<p>This is the home page for the Flowers app.</p>
	<%= link_to "Pick", all_path, class: "btn btn-primary btn-lg" %>
</div>